# Generated by Django 5.1.4 on 2026-09-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_options_alter_customuser_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_reminder_sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last reminder sent'),
        ),
    ]
