# Generated by Django 5.1.4 on 2026-06-07 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leagues', '0001_initial'),
        ('matches', '0004_alter_competition_external_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0, verbose_name='Points')),
                ('prediction_count', models.IntegerField(default=0, verbose_name='Predictions scored')),
                ('exact_count', models.IntegerField(default=0, verbose_name='Exact scores')),
                ('gap_count', models.IntegerField(default=0, verbose_name='Good gaps')),
                ('win_count', models.IntegerField(default=0, verbose_name='Correct winners')),
                ('rank', models.IntegerField(blank=True, null=True, verbose_name='Rank')),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matches.competition', verbose_name='Competition')),
                ('league', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leagues.league', verbose_name='League')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_scores', to=settings.AUTH_USER_MODEL, verbose_name='Player')),
            ],
            options={
                'verbose_name': 'User score',
                'verbose_name_plural': 'User scores',
                'indexes': [models.Index(fields=['competition', 'league'], name='userscore_scope_idx')],
            },
        ),
    ]
