# Generated by Django 5.1.4 on 2026-09-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
        ('matches', '0004_alter_competition_external_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='competitions',
            field=models.ManyToManyField(related_name='leagues', to='matches.competition', verbose_name='Competitions'),
        ),
    ]
