# Generated by Django 5.1.4 on 2026-09-02 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0002_league_competitions'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='end_date',
            field=models.DateField(blank=True, help_text='League is automatically deactivated after this date. Leave blank for no expiry.', null=True, verbose_name='End date'),
        ),
    ]
