# Generated by Django 5.1.4 on 2026-09-02 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0003_league_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='end_date',
        ),
    ]
