# Generated by Django 5.1.4 on 2026-05-21 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(unique=True, verbose_name='ID RapidAPI')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('code', models.CharField(help_text='Ex: TOP14, CHAMP_CUP, SIX_NATIONS', max_length=20, verbose_name='Code court')),
                ('country', models.CharField(max_length=100, verbose_name='Pays / Zone')),
                ('logo_url', models.URLField(blank=True, verbose_name='URL du logo')),
                ('season', models.CharField(help_text='Ex: 2024-2025', max_length=20, verbose_name='Saison')),
                ('is_active', models.BooleanField(default=True, verbose_name='Compétition active')),
                ('scoring_system', models.CharField(default='COTES', help_text='COTES = basé sur les cotes, FIXED = points fixes', max_length=10, verbose_name='Système de points')),
                ('good_gap_pts', models.IntegerField(default=3, verbose_name='Seuil bon écart (pts)')),
            ],
            options={
                'verbose_name': 'Compétition',
                'verbose_name_plural': 'Compétitions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(unique=True, verbose_name='ID RapidAPI')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('short_name', models.CharField(blank=True, help_text='Ex: STA, ASM, LOU', max_length=20, verbose_name='Nom court')),
                ('logo_url', models.URLField(blank=True, verbose_name='URL du logo')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Pays')),
            ],
            options={
                'verbose_name': 'Équipe',
                'verbose_name_plural': 'Équipes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(unique=True, verbose_name='ID RapidAPI')),
                ('round', models.CharField(blank=True, help_text='Ex: J12, Demi-finale', max_length=50, verbose_name='Journée / Tour')),
                ('datetime', models.DateTimeField(verbose_name="Date et heure du coup d'envoi")),
                ('venue', models.CharField(blank=True, max_length=200, verbose_name='Stade')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Planifié'), ('IN_PLAY', 'En cours'), ('FINISHED', 'Terminé'), ('POSTPONED', 'Reporté'), ('CANCELLED', 'Annulé')], default='SCHEDULED', max_length=20, verbose_name='Statut')),
                ('home_score', models.IntegerField(blank=True, null=True, verbose_name='Score domicile')),
                ('away_score', models.IntegerField(blank=True, null=True, verbose_name='Score extérieur')),
                ('cote_home', models.IntegerField(blank=True, null=True, verbose_name='Cote domicile (×10)')),
                ('cote_draw', models.IntegerField(blank=True, null=True, verbose_name='Cote nul (×10)')),
                ('cote_away', models.IntegerField(blank=True, null=True, verbose_name='Cote extérieur (×10)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='matches.competition', verbose_name='Compétition')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='matches.team', verbose_name='Équipe extérieur')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='matches.team', verbose_name='Équipe domicile')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matchs',
                'ordering': ['datetime'],
            },
        ),
    ]
