# Generated by Django 5.1.4 on 2026-05-21 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'ordering': ['name'], 'verbose_name': 'Competition', 'verbose_name_plural': 'Competitions'},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['datetime'], 'verbose_name': 'Match', 'verbose_name_plural': 'Matches'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name'], 'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
        migrations.AddField(
            model_name='match',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='If True, this match is not shown to users in the prediction UI.', verbose_name='Hidden'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='code',
            field=models.CharField(help_text='e.g. TOP14, CHAMP_CUP, SIX_NATIONS', max_length=20, verbose_name='Short code'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='country',
            field=models.CharField(max_length=100, verbose_name='Country / Zone'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='external_id',
            field=models.IntegerField(unique=True, verbose_name='RapidAPI ID'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='good_gap_pts',
            field=models.IntegerField(default=3, verbose_name='Good gap threshold (pts)'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active competition'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='logo_url',
            field=models.URLField(blank=True, verbose_name='Logo URL'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='scoring_system',
            field=models.CharField(default='COTES', help_text='COTES = odds-based, FIXED = flat points', max_length=10, verbose_name='Scoring system'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='season',
            field=models.CharField(help_text='e.g. 2024-2025', max_length=20, verbose_name='Season'),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Away score'),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='matches.team', verbose_name='Away team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='matches.competition', verbose_name='Competition'),
        ),
        migrations.AlterField(
            model_name='match',
            name='cote_away',
            field=models.IntegerField(blank=True, null=True, verbose_name='Away odds (×10)'),
        ),
        migrations.AlterField(
            model_name='match',
            name='cote_draw',
            field=models.IntegerField(blank=True, null=True, verbose_name='Draw odds (×10)'),
        ),
        migrations.AlterField(
            model_name='match',
            name='cote_home',
            field=models.IntegerField(blank=True, null=True, verbose_name='Home odds (×10)'),
        ),
        migrations.AlterField(
            model_name='match',
            name='datetime',
            field=models.DateTimeField(verbose_name='Kickoff date and time'),
        ),
        migrations.AlterField(
            model_name='match',
            name='external_id',
            field=models.IntegerField(unique=True, verbose_name='RapidAPI ID'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Home score'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='matches.team', verbose_name='Home team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='round',
            field=models.CharField(blank=True, help_text='e.g. 1, 22, Semi-final, Final', max_length=50, verbose_name='Round'),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PLAY', 'In play'), ('FINISHED', 'Finished'), ('POSTPONED', 'Postponed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='match',
            name='venue',
            field=models.CharField(blank=True, max_length=200, verbose_name='Venue'),
        ),
        migrations.AlterField(
            model_name='team',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='team',
            name='external_id',
            field=models.IntegerField(unique=True, verbose_name='RapidAPI ID'),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo_url',
            field=models.URLField(blank=True, verbose_name='Logo URL'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='team',
            name='short_name',
            field=models.CharField(blank=True, help_text='e.g. STA, ASM, LOU', max_length=20, verbose_name='Short name'),
        ),
    ]
