# Generated by Django 5.1.4 on 2026-05-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_alter_competition_options_alter_match_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='external_id',
            field=models.IntegerField(verbose_name='RapidAPI ID'),
        ),
        migrations.AlterUniqueTogether(
            name='competition',
            unique_together={('external_id', 'season')},
        ),
    ]
