# Generated by Django 5.1.4 on 2026-06-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_competition_unique_external_id_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='external_id',
            field=models.IntegerField(verbose_name='API ID'),
        ),
        migrations.AlterField(
            model_name='match',
            name='external_id',
            field=models.IntegerField(unique=True, verbose_name='API ID'),
        ),
        migrations.AlterField(
            model_name='team',
            name='external_id',
            field=models.IntegerField(unique=True, verbose_name='API ID'),
        ),
    ]
