# Generated by Django 5.1.4 on 2026-09-02 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_alter_competition_external_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='end_date',
            field=models.DateField(blank=True, help_text="Run 'deactivate_ended_competitions' to auto-set is_active=False after this date.", null=True, verbose_name='End date'),
        ),
    ]
