# Generated by Django 5.1.4 on 2026-09-03 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_competition_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='logo_url',
        ),
    ]
